# Generated by Django 4.1.7 on 2023-03-03 21:10

import apps.brands.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(upload_to=apps.brands.models.Brand.brand_media_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brand')),
                ('category', models.ManyToManyField(to='brands.category')),
            ],
            options={
                'verbose_name': 'Inventory Item',
            },
        ),
        migrations.CreateModel(
            name='InventoryItemColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.inventoryitem')),
            ],
            options={
                'verbose_name': 'Inventory Item Color',
            },
        ),
        migrations.CreateModel(
            name='InventoryItemColorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.brands.models.InventoryItemColorImage.item_media_directory_path)),
                ('inventory_item_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.inventoryitemcolor')),
            ],
            options={
                'verbose_name': 'Inventory Item Color Image',
            },
        ),
        migrations.CreateModel(
            name='SearchListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('priority', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.category')),
            ],
            options={
                'verbose_name': 'Search List Item',
                'unique_together': {('category', 'priority'), ('name', 'category')},
            },
        ),
    ]
