# Generated by Django 4.1.7 on 2023-03-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitemcolorimage',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
