# Generated by Django 4.1.7 on 2023-03-03 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_inventoryitemcolorimage_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryitemcolor',
            unique_together={('inventory_item', 'color')},
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitemcolorimage',
            unique_together={('inventory_item_color', 'order')},
        ),
    ]
