# Generated by Django 4.1.7 on 2023-03-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_alter_inventoryitemcolor_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitemcolor',
            name='price',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitemcolor',
            name='stock',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
