# Generated by Django 4.1.7 on 2023-03-16 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('brands', '0004_inventoryitemcolor_price_inventoryitemcolor_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchListItem',
            new_name='ClothingType',
        ),
        migrations.AlterModelOptions(
            name='clothingtype',
            options={'verbose_name': 'Clothing Type'},
        ),
        migrations.RenameField(
            model_name='clothingtype',
            old_name='priority',
            new_name='search_list_priority',
        ),
        migrations.AlterUniqueTogether(
            name='clothingtype',
            unique_together={('name', 'category'), ('category', 'search_list_priority')},
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='inventoryitemcolor',
            name='stock',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='clothing_type_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clothing_type_1', to='brands.clothingtype'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='clothing_type_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clothing_type_2', to='brands.clothingtype'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='clothing_type_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clothing_type_3', to='brands.clothingtype'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='clothing_type_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clothing_type_4', to='brands.clothingtype'),
        ),
        migrations.AddField(
            model_name='inventoryitemcolor',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='InventoryItemColorSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('xxxsmall', 'XXXS'), ('xxsmall', 'XXS'), ('xsmall', 'XS'), ('small', 'S'), ('medium', 'M'), ('large', 'L'), ('xlarge', 'XL'), ('xxlarge', 'XXL'), ('xxxlarge', 'XXXL')], max_length=50)),
                ('stock', models.IntegerField()),
                ('inventory_item_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.inventoryitemcolor')),
            ],
            options={
                'verbose_name': 'Inventory Item Color Size',
                'unique_together': {('inventory_item_color', 'size')},
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brand')),
            ],
            options={
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brands.collection'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CustomerFavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.inventoryitemcolor')),
            ],
            options={
                'verbose_name': 'User Favorite Item',
                'unique_together': {('customer', 'item')},
            },
        ),
        migrations.CreateModel(
            name='CustomerFavoriteBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brand')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
            options={
                'verbose_name': 'User Favorite Brand',
                'unique_together': {('customer', 'brand')},
            },
        ),
        migrations.CreateModel(
            name='CustomerBagItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.inventoryitemcolorsize')),
            ],
            options={
                'verbose_name': 'User Bag',
                'unique_together': {('customer', 'item')},
            },
        ),
    ]
