# Generated by Django 4.1.7 on 2023-03-16 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_rename_searchlistitem_clothingtype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerbagitem',
            options={'verbose_name': 'Customer Bag Item'},
        ),
        migrations.AlterModelOptions(
            name='customerfavoritebrand',
            options={'verbose_name': 'Customer Favorite Brand'},
        ),
        migrations.AlterModelOptions(
            name='customerfavoriteitem',
            options={'verbose_name': 'Customer Favorite Item'},
        ),
    ]
