# Generated by Django 4.1.7 on 2023-03-17 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0006_alter_customerbagitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('show_on_home_page', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('section_type', models.CharField(choices=[('item_image', 'Item Image'), ('brand_image', 'Brand Image'), ('items', 'Items'), ('brands', 'Brands')], max_length=50)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='brands.brand')),
                ('brands', models.ManyToManyField(blank=True, related_name='brands', to='brands.brand')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='brands.inventoryitemcolor')),
                ('items', models.ManyToManyField(blank=True, related_name='items', to='brands.inventoryitemcolor')),
            ],
            options={
                'verbose_name': 'Home Page Section',
            },
        ),
    ]
