# Generated by Django 4.1.7 on 2023-03-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0008_clothingtype_shown_in_search_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesection',
            name='text',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
