# Generated by Django 4.1.7 on 2023-03-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0009_alter_homepagesection_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothingtype',
            old_name='shown_in_search_list',
            new_name='show_in_search_list',
        ),
    ]
