# Generated by Django 4.1.7 on 2023-03-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0010_rename_shown_in_search_list_clothingtype_show_in_search_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesection',
            name='order',
            field=models.IntegerField(unique=True),
        ),
    ]
