# Generated by Django 4.1.7 on 2023-03-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0011_alter_homepagesection_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='clothing_type_1',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='clothing_type_2',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='clothing_type_3',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='clothing_type_4',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='clothing_types',
            field=models.ManyToManyField(blank=True, to='brands.clothingtype'),
        ),
    ]
