# Generated by Django 4.1.7 on 2023-03-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0012_remove_inventoryitem_clothing_type_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitemcolorsize',
            name='size',
            field=models.CharField(choices=[('xxxsmall', '3XS'), ('xxsmall', '2XS'), ('xsmall', 'XS'), ('small', 'S'), ('medium', 'M'), ('large', 'L'), ('xlarge', 'XL'), ('xxlarge', '2XL'), ('xxxlarge', '3XL')], max_length=50),
        ),
    ]
