# Generated by Django 4.1.7 on 2023-03-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0013_alter_inventoryitemcolorsize_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
